### ISSUE TITLE
Logging and comments API download

### ISSUE THREAD

**Issue by martinpeterr** [vanderbilt-redcap/api-sync-module#1]
# Logging and Comments Metadata

Hi,

_I'm not sure in which repository to open this ticket -- if you feel this is incorrect, please direct me to where would be more approprite, thank you._

I would like to be able to pull the logging and comment data from a project (metadata) -- Is there any way to add this functionality? It seems like the API is able to do pretty much everything else.

Thanks!
Pete

PS. _Currently the `exportMetaData()` function might be more aptly named `exportDataDictionary`, since it returns the data dictionary regardless of arguments passed._
PPS. _first ever github issue opened_

**Comment by mmcev106** [comment]
It sounds like you're requesting changes to the API calls that REDCap itself supports.  This module simply utilizes some of the APIs that REDCap supports.  These questions likely belong in the [community forum](https://community.projectredcap.org/).
