### ISSUE TITLE
CURL Error: OpenSSL SSL_connect: SSL_ERROR_SYSCALL

### ISSUE THREAD

**Issue by gardiners** [vanderbilt-redcap/api-sync-module#10]
Hi Mark and Carl,

I'm on REDCap 10.8.1 and PHP 7.4.6 (Windows OS) on IIS.

I've set up an import and have attempted both a scheduled and an "Import Now" import. I'm given the following error and stack trace in the log (secrets redacted):

```
CURL Error: OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to redacted_url.org.au:443 
#0 C:\inetpub\redcap\modules\api_sync_v1.6.0\APISyncExternalModule.php(766): Vanderbilt\APISyncExternalModule\APISyncExternalModule->apiRequest('https://redacted....', 'REDACTED_TOKEN...', Array)
#1 C:\inetpub\redcap\modules\api_sync_v1.6.0\APISyncExternalModule.php(571): Vanderbilt\APISyncExternalModule\APISyncExternalModule->getProjectTitle('https://redacted....', 'REDACTED_TOKEN...')
#2 C:\inetpub\redcap\modules\api_sync_v1.6.0\APISyncExternalModule.php(427): Vanderbilt\APISyncExternalModule\APISyncExternalModule->importNextBatch(Object(Vanderbilt\APISyncExternalModule\Progress))
#3 C:\inetpub\redcap\modules\api_sync_v1.6.0\APISyncExternalModule.php(36): Vanderbilt\APISyncExternalModule\APISyncExternalModule->handleImports()
#4 C:\inetpub\redcap\redcap_v10.8.1\ExternalModules\classes\ExternalModules.php(5214): Vanderbilt\APISyncExternalModule\APISyncExternalModule->cron(Array)
#5 C:\inetpub\redcap\redcap_v10.8.1\Classes\Cron.php(305): ExternalModules\ExternalModules::callCronMethod('50', 'imports')
#6 C:\inetpub\redcap\redcap_v10.8.1\cron.php(20): Cron->execute()
#7 C:\inetpub\redcap\cron.php(9): include('C:\\inetpub\\redc...')
#8 {main}
```

I can successfully import from our own test sever (also over SSL). I guess the error could be a result of the SSL capabilities of the source server - I'll give it a deep portscan and learn a bit more about it when I am on a less monitored network. 

Any ideas?

**Comment by mmcev106** [comment]
@gardiners, I'm afraid this particular error does not ring any bells for me.  I'd just have to google it...  I would strongly suspect it is some kind of general SSL issue with that server, as the requests this module makes is quite basic.  Does HTTPS work without any warnings when you access that server through a browser?  I'm going to go ahead and close this as we are not able to offer general network/server support.  Please feel free to re-open it if you're able to pinpoint the problem and have an idea for a module update that might help with in this case.
