### ISSUE TITLE
Error when upgrading 11.0

### ISSUE THREAD

**Issue by Harinivenk** [vanderbilt-redcap/api-sync-module#14]
Hi , I was using Api-Sync 5.0 

Please help me !! Is there any setting to be done when i upgrade ?

Now when i upgrade it to 11.0 Iam getting this error . I am not able to go to configure translation page as well . 
screen shot attached 
 ![crash'](https://user-images.githubusercontent.com/22289151/150930236-24ebb426-91aa-45ab-a545-94318a8f4f94.JPG)
[](url)

Cron job 'exports' failed for External Module 'api_sync'.

Exception: TypeError: array_filter(): Argument #1 ($array) must be of type array, null given in /home/ec2-user/project/redcap/modules/api_sync_v1.11.0/APISyncExternalModule.php:885
Stack trace:
#0 /home/ec2-user/project/redcap/modules/api_sync_v1.11.0/APISyncExternalModule.php(885): array_filter(NULL)
#1 /home/ec2-user/project/redcap/modules/api_sync_v1.11.0/APISyncExternalModule.php(844): Vanderbilt\APISyncExternalModule\APISyncExternalModule->filterByFieldList(Array, Array)

#2 /home/ec2-user/project/redcap/modules/api_sync_v1.11.0/APISyncExternalModule.php(475): Vanderbilt\APISyncExternalModule\APISyncExternalModule->prepareData(Array, Array, 'record_id')
#3 /home/ec2-user/project/redcap/modules/api_sync_v1.11.0/APISyncExternalModule.php(401): Vanderbilt\APISyncExternalModule\APISyncExternalModule->exportSubBatch(Array, 'update', Array, 1)
#4 /home/ec2-user/project/redcap/modules/api_sync_v1.11.0/APISyncExternalModule.php(95): Vanderbilt\APISyncExternalModule\APISyncExternalModule->export(Array)
#5 /home/ec2-user/project/redcap/modules/api_sync_v1.11.0/APISyncExternalModule.php(48): Vanderbilt\APISyncExternalModule\APISyncExternalModule->handleExports()
#6 /home/ec2-user/project/redcap/redcap_v11.4.0/ExternalModules/classes/ExternalModules.php(5404): Vanderbilt\APISyncExternalModule\APISyncExternalModule->cron(Array)
#7 /home/ec2-user/project/redcap/redcap_v11.4.0/Classes/Cron.php(305): ExternalModules\ExternalModules::callCronMethod('2', 'exports')
#8 /home/ec2-user/project/redcap/redcap_v11.4.0/cron.php(20): Cron->execute()
#9 /home/ec2-user/project/redcap/cron.php(9): include('/home/ec2-user/...')
#10 {main}

**Comment by mmcev106** [comment]
These were two different PHP8 specific bugs that I just fixed and included in release 1.11.2.  Thanks very much for reporting this with the stack trace!  Let me know if you see any other issues.

**Comment by Harinivenk** [comment]
Hi Thanks Mark ,

Thanks a ton Mark ,

though my previous issue got corrected . Now I have these new issues .


The sync is working perfectly well for smaller projects . But when I am
trying to port data from a bigger project A  (20 K data with 560 fields )
to Project B (45K data with 1700 fields ) both residing in the same server
I am getting this error. I have settings in Api sync as attached in the
screenshot . is there any modification i can do to remove the

[image: max record size.JPG]

An empty response was received.  Automatic batch sizes may be too
large, causing the remote server to run out of memory when parsing the
request.  Please try reducing the batch or sub-batch size, and report
this error to ***@***.*** so automatic batch size detection can
be improved in this case.

#0 /home/ec2-user/project/redcap/modules/api_sync_v1.11.3/APISyncExternalModule.php(501):
Vanderbilt\APISyncExternalModule\APISyncExternalModule->apiRequest('https://prevent...',
'51FFD8CFB1B2FE6...', Array)
#1 /home/ec2-user/project/redcap/modules/api_sync_v1.11.3/APISyncExternalModule.php(411):
Vanderbilt\APISyncExternalModule\APISyncExternalModule->exportSubBatch(Array,
'update', Array, 1)
#2 /home/ec2-user/project/redcap/modules/api_sync_v1.11.3/APISyncExternalModule.php(95):
Vanderbilt\APISyncExternalModule\APISyncExternalModule->export(Array)
#3 /home/ec2-user/project/redcap/modules/api_sync_v1.11.3/APISyncExternalModule.php(48):
Vanderbilt\APISyncExternalModule\APISyncExternalModule->handleExports()
#4 /home/ec2-user/project/redcap/redcap_v11.4.0/ExternalModules/classes/ExternalModules.php(5404):
Vanderbilt\APISyncExternalModule\APISyncExternalModule->cron(Array)
#5 /home/ec2-user/project/redcap/redcap_v11.4.0/Classes/Cron.php(305):
ExternalModules\ExternalModules::callCronMethod('2', 'exports')
#6 /home/ec2-user/project/redcap/redcap_v11.4.0/cron.php(20): Cron->execute()
#7 /home/ec2-user/project/redcap/cron.php(9): include('/home/ec2-user/...')
#8 {main}

**Comment by mmcev106** [comment]
The way data is distributed between instruments can vary wildly on large projects, and the default settings may not work in some cases.  I think the error message frames the required course of action pretty well.  The `Max Megabytes Per Sub-Batch` setting defaults to `7` on recent API Sync versions.  To start, you could try reducing it to `3` or `4`.  If the issue is related to request size limits on your server/network, you'll just have to find the right size that falls under that limit (without being so small that the sync takes too long).
