### ISSUE TITLE
PHP 8 Compatibility

### ISSUE THREAD

**Issue by kaizentowfiq** [vanderbilt-redcap/api-sync-module#18]
Hello,

We recently noticed a php 8 related bug on the config translations page.  This happened on REDCap version 13.1.15 as well as 13.1.9.

Here's a screenshot of the issue:
<img width="734" alt="Screen Shot 2023-03-27 at 9 18 46 AM" src="https://user-images.githubusercontent.com/25359085/228002026-d4b1bdf1-4550-4f81-9d5d-785d637690bb.png">

It looks like replacing line 144 in config_translations.php with
```$project['project-index'] = strval((int)$project_i + 1);```
resolved the issue, although strval() might not be necessary in that line.

After i resolved that php 8 issue, I noticed that the the form translations and event translations tables weren't rendering despite the EM successfully saving form and event translations to the project settings.

After some debugging, i think i found out why the translations tables weren't rendering properly.  In config_translations.php, it looks like the code expects the form translations and event translations to be returned by `$module->getSubSettings('servers');`.  However, when i inspected the object, i didn't see the form translations or event translations that I successfully saved through the EM's UI even though i could see they were successfully saved in the database.  I noticed that the form translations and event translations were returned by `$project_settings = $module->getProjectSettings('servers');`, and I also noticed what I think is an appropriate pattern to map the translations returned by `getProjectSettings('servers')` into the object returned by `getSubSettings('servers')` so that the rest of the code works as-is.

here's the snippet I added to config_translations.php on line 23 right after $import_servers is defined:
```
$project_settings = $module->getProjectSettings('servers');

# remap form and event translations from project settings into server subsettings object
$form_translations = $project_settings['form-translations'];
$event_translations = $project_settings['event-translations'];

foreach ($import_servers as $server_index => $server) {
        foreach ($import_servers[$server_index]['projects'] as $project_index => $project_info) {
                if (array_key_exists($server_index, $form_translations)) {
                        if (array_key_exists((int)$project_index, $form_translations[$server_index])) {
                                if ($form_translations[$server_index][(int)$project_index] != '[[""]]') {
                                        $import_servers[$server_index]['projects'][$project_index]['form-translations'] = $form_translations[$server_index][(int)$project_index];
                                }
                        }
                }
                if (array_key_exists($server_index, $event_translations)) {
                        if (array_key_exists((int)$project_index, $event_translations[$server_index])) {
                                if ($form_translations[$server_index][(int)$project_index] != '[[""]]') {
                                        $import_servers[$server_index]['projects'][$project_index]['event-translations'] = $event_translations[$server_index][(int)$project_index];
                                }
                        }
                }
        }
}
```
After i added that, the translations tables on the config_translations.php page were rendering properly.  I didn't investigate further to see if a similar fix works for the export servers.  I'm not sure if what I did is a full or proper fix for the issue, but thought i'd share it in case it helps with your own debugging.

**Comment by mmcev106** [comment]
Thanks very much for reporting these, and finding solutions!  I believe 1.11.12 should fix both problems.  The sub settings issue was related to those settings being marked as "hidden" in config.json.  I'm going to release a version of the module framework shortly that allows hidden settings to be included in the response from `getSubSettings()` calls.

**Comment by kaizentowfiq** [comment]
awesome, thanks @mmcev106!
