### ISSUE TITLE
Error deleting records when using record id prefix

### ISSUE THREAD

**Issue by highball-it** [vanderbilt-redcap/api-sync-module#2]
When syncing a deleted record the record id prefix is not prepended and the remote REDCap server is returning an error 400

`HTTP error code 400 received: {"error":"One or more of the records provided cannot be deleted because they do not exist in the project. The following records do not exist: <RECORD_ID_WITHOUT_SUFFIX>"}`

**Comment by mmcev106** [comment]
This module does not currently have a support budget unfortunately...

**Comment by mmcev106** [comment]
PR #3 has been merged & deployed in release 1.2.2.  Thanks again for the PR!
