### ISSUE TITLE
recognition  of new records when created via api 

### ISSUE THREAD

**Issue by Harinivenk** [vanderbilt-redcap/api-sync-module#4]
Hi 

I am using apisync module in my project extensively . A big thanks for the same ... it is such a good feature ....however ..I have noticed one issue ...My project setup  is as follows 

Project A  (for center A )
Project B (for center B)
Project C (for center C)

From Project A, B , C , the data gets moved to Project D  via apisync(runing at a particular hour daily ) . In project D there are various checks after which it should move to Project E (Via Apisync )  where data is finally stored . Currently the same is not happening ... only export all is working .... as  new records added via API sync is not getting recorgnised as new  records added .. 

is the new records created getting recognised , when the new records is created via api ? 

Thanks 
Harini

**Comment by mmcev106** [comment]
I should say up front that I only have very limited time to spend even communicating about this module because it does not have a support budget currently.  I'll try to help as much as I can though.

I don't think a multiproject setup would affect the way the module works, so I would focus troubleshooting on the specific sync configuration that is not working.  Are any error messages appearing in the log on the "API Sync" page around the time that the sync should be running?  What specifically do you mean by "not getting recognised as new records added"?

**Comment by Harinivenk** [comment]
Thanks , That s so kind of you . 

There are no errors in the api ysnc .. My guess is when a record is imported to the project via any form ( from the redcap mobile form or from api  or any import ) .. is there any difference in the logging ... .. when a  new record is created via api and and when it is created manually is there a difference ... .. which is why api-sync is not recongnising the  new records created via api .... or through import ... but is recognising when i update a  exisiting record manually ... which table should i look for .. if you have any idea on the same .. i would gladly help u .

**Comment by mmcev106** [comment]
I think I just now am understanding the scenario.  I have not verified this, but it sounds like API imports do not trigger the `redcap_save_record` hook, which is what the export feature uses to detect which records need to be synced.  An easy workaround would be to instead configure the API Sync module on the destination project using the import feature.  The import feature always syncs all records, regardless of whether they've changed.

**Comment by Harinivenk** [comment]
Thanks,  I looked into this option as well .. but the problem was the massive data we have ... we are per day collecting around 150 records... importing daily would increase the load on the mysql as the project is expected to grow very large around 30,000 records with 2000 fields

**Comment by mmcev106** [comment]
Understood.  I think the module would need to be modified to support this scenario.  Three possible solution come to mind off the top of my head:
- Detect import requests in one of the "every page" hooks and mark imported records for export
- Adding a new API call via the module (which is much easier than it sounds) which can be used to mark recently exported records for export again on the remote system
- Adding a new API call via this or another module that triggers the `redcap_save_record` hook

I am only able to work on one of the above if someone funds the work.  On my own time I may be able to review/merge a pull request if someone else wanted to make one of the above changes.

**Comment by mmcev106** [comment]
This behavior should be supported as of 1.6.0!  Another project I was working on had a similar need, and requested change detection via querying the log table rather than hooks.

**Comment by Harinivenk** [comment]
That s a great news.. really indebted to you for this change .. this would
make thinks so easier in our project .
