### ISSUE TITLE
More than 1 Import Project does not work

### ISSUE THREAD

**Issue by 274188A** [vanderbilt-redcap/api-sync-module#7]
no error, just does not process the 2nd import project configured.  doubled checked the api keys etc.  not idea...

**Comment by mmcev106** [comment]
@274188A, I just wanted to let you know I saw this.  The import feature is not currently used by any projects with a module support budget, but I have a little bit of flexible time that I can use to look into this.  It's on the TODO list...

**Comment by mmcev106** [comment]
@274188A, I just tested this and was able to import from two projects in a basic configuration example.  I did notice that they did NOT occur in the same cron run (the second project didn't start until the next minute).  Perhaps this is what you were seeing?  Feel free to reopen this if you're still seeing the issue and can provide more info (perhaps a data dictionary).
